#!/bin/bash
cd /root/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/tpope/vim-rails.git
git clone https://github.com/wincent/command-t.git
git clone https://github.com/vim-ruby/vim-ruby.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/tpope/vim-endwise.git
git clone https://github.com/ervandew/supertab.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/terryma/vim-multiple-cursors.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/itchyny/lightline.vim.git
git clone https://github.com/kchmck/vim-coffee-script.git
git clone https://github.com/elixir-lang/vim-elixir.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/pangloss/vim-javascript.git                                           
git clone https://github.com/godlygeek/tabular.git                                                 
git clone https://github.com/Raimondi/delimitMate.git                                              
git clone https://github.com/nathanaelkane/vim-indent-guides.git                                   
git clone https://github.com/groenewege/vim-less.git                                               
git clone https://github.com/othree/html5.vim.git                                                  
git clone https://github.com/elzr/vim-json.git                                                     
git clone https://github.com/bling/vim-airline.git                                                 
git clone https://github.com/easymotion/vim-easymotion.git                                         
git clone https://github.com/mbbill/undotree.git                                                   
git clone https://github.com/majutsushi/tagbar.git                                                 
git clone https://github.com/vim-scripts/EasyGrep.git                                              
git clone https://github.com/jlanzarotta/bufexplorer.git                                           
git clone https://github.com/kien/ctrlp.vim.git                                                    
git clone https://github.com/jistr/vim-nerdtree-tabs.git                                           
git clone https://github.com/tomtom/tlib_vim.git                                                   
git clone https://github.com/marcweber/vim-addon-mw-utils.git                                      
git clone https://github.com/altercation/vim-colors-solarized.git                                  
git clone https://github.com/vim-scripts/taglist.vim.git                                           
git clone https://github.com/terryma/vim-expand-region.git                                         
git clone https://github.com/fatih/vim-go.git                                                      
git clone https://github.com/plasticboy/vim-markdown.git                                           
git clone https://github.com/michaeljsmith/vim-indent-object.git                                   
git clone https://github.com/tpope/vim-repeat.git                                                  
git clone https://github.com/tpope/vim-surround.git                                                
git clone https://github.com/vim-scripts/mru.vim.git                                               
git clone https://github.com/vim-scripts/YankRing.vim.git                                          
git clone https://github.com/tpope/vim-haml.git                                                    
git clone https://github.com/SirVer/ultisnips.git                                                  
git clone https://github.com/honza/vim-snippets.git                                                
git clone https://github.com/derekwyatt/vim-scala.git                                              
git clone https://github.com/leafgarland/typescript-vim.git                                        
git clone https://github.com/christoomey/vim-tmux-navigator.git                                    
git clone https://github.com/Quramy/tsuquyomi.git                                                  
git clone https://github.com/ekalinin/Dockerfile.vim.git
